### ISSUE TITLE
Щелчёк

### ISSUE THREAD

**Issue by sergeyfil1** [yangxiaohua2009/custom-kernel#1]
При запуске системы издаеться громкий щелчёк, как это можно убрать?

**Comment by Ailontania** [comment]
> При запуске системы издаеться громкий щелчёк, как это можно убрать?

亲爱的俄罗斯老哥，你写俄语别人看不懂呀。
要想让别人看得懂，应该像我一样，写汉语 ：P <手动滑稽>

对呀，系统启动时有很大的咔哒声，如何解决？
