### ISSUE TITLE
sof_2_8.zip does not work

### ISSUE THREAD

**Issue by Ailontania** [yangxiaohua2009/custom-kernel#2]
[sof_2_8.zip](https://github.com/yangxiaohua2009/custom-kernel/blob/main/sof_2_8.zip) version does not work.
kernel.zip version works.

Hardware:
 KUU yobook

**Comment by yangxiaohua2009** [comment]
> [sof_2_8.zip](https://github.com/yangxiaohua2009/custom-kernel/blob/main/sof_2_8.zip) version does not work. kernel.zip version works.
> 
> Hardware: KUU yobook

If you want to use [sof_2_8.zip](https://github.com/yangxiaohua2009/custom-kernel/blob/main/sof_2_8.zip) version,
backup and copy all tplg from es8336-topologies-2.tar.gz to /lib/firmware/intel/sof-tplg and use dmesg to see if there is an error.
