### ISSUE TITLE
sof.zip - cannot extract

### ISSUE THREAD

**Issue by KrychaTech** [yangxiaohua2009/custom-kernel#3]
sof.zip file seems corrupted, as you get an error while trying to extract it. here's the output from "unzip sof.zip":

`Archive:  sof.zip
warning [sof.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
file #2:  bad zipfile offset (local header sig):  8474834
  inflating: linux-libc-dev_5.16.0-rc1-tgl-55_amd64.deb  
`
it might be a problem on my side, but if isn't please replace the file with a working one.

**Comment by yangxiaohua2009** [comment]
Your achieve manager does not support multi-parted zip.
Please install achieve manager like [peazip](https://peazip.github.io/peazip-linux.html) to fix this.

**Comment by KrychaTech** [comment]
Thanks a bunch, gonna try it later
